In [8]:
with open('/home/devel/workspaces/finest_mobility/src/data_unpack/config/', 'rb') as _fd:
    s = _fd.read()

In [9]:
print(s.decode('utf8'))

P2:  1359.40979 0. 917.3976 0. 0. 1523.71069 546.10493 0. 0. 0. 1. 0.
R0_rect:  1. 0. 0. 0. 1. 0. 0. 0. 1.
Tr_velo_to_cam: -0.0361133 -0.99835228 0.04459329 0.05 -0.02594949 -0.04367056 -0.99870892 -0.013 0.99901074 -0.03722384 -0.02432964 -0.075


In [3]:
import pickle

In [6]:
import numpy as np

In [7]:
tr_velo_cam = np.asarray([
    [-3.6113295780354937e-02, -9.9835227648545777e-01,  4.4593294385862348e-02,  0.07],
    [-2.5949489152197913e-02, -4.3670556292665141e-02, -9.9870891981889720e-01, -0.25],
    [ 9.9901073762028203e-01, -3.7223843828824987e-02, -2.4329643852442184e-02, -0.4]])

In [32]:
tr_radar_cam = np.asarray([
    [ -0.0361133, -0.99835228,  0.04459329,  0.05 ],
    [-0.02594949, -0.04367056, -0.99870892, -0.013],
    [ 0.99901074, -0.03722384, -0.02432964, -0.075]])

In [28]:
tr_radar_cam = Rotation.from_euler('xyz',(.0,.0,.0), degrees=True).as_matrix()

In [30]:
np.linalg.inv(tr_radar_cam)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
from scipy.spatial.transform import Rotation

In [26]:
np.rad2deg(Rotation.from_matrix(tr_velo_cam[:,:-1]).as_euler('xyz'))

array([-123.16878121,  -87.45123857, -144.30057167])

In [24]:
Rotation.from_euler('xyz', 0-np.rad2deg(Rotation.from_matrix(tr_velo_cam[:,:-1]).as_euler('xyz')),
                    degrees=True).as_matrix()

array([[-0.0361133 , -0.35984193,  0.93231412],
       [ 0.02594949,  0.93227044,  0.36083023],
       [-0.99901074,  0.03722384, -0.02432964]])

In [18]:
np.rad2deg(Rotation.from_matrix(np.linalg.inv(np.asmatrix(tr_velo_cam[:,:-1]))).as_euler('xyz'))

array([-91.39551197,  -2.55585512, -92.07165117])

In [16]:
np.rad2deg(Rotation.from_matrix(tr_radar_cam[:,:-1]).as_euler('xyz'))

array([-123.16876802,  -87.45123872, -144.30058456])

In [34]:
tr_radar_cam[:,-1], tr_velo_cam[:,-1]

(array([ 0.05 , -0.013, -0.075]), array([ 0.07, -0.25, -0.4 ]))

In [35]:
tr_velo_radar = np.asarray([
    [-0.0361133 , -0.35984193,  0.93231412,  0.2  ],
    [ 0.02594949,  0.93227044,  0.36083023, -0.237],
    [-0.99901074,  0.03722384, -0.02432964, -0.325]])

In [36]:
import sys

In [37]:
sys.path.append('/home/devel/workspaces/finest_mobility/src/data_unpack/src')

In [38]:
from lidar_camera_projection import read_calib_file

In [39]:
read_calib_file('/home/devel/workspaces/finest_mobility/src/data_unpack/config/lidar_cam_calib.txt')

{'P2': array([1.35940979e+03, 0.00000000e+00, 9.17397600e+02, 0.00000000e+00,
        0.00000000e+00, 1.52371069e+03, 5.46104930e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00]),
 'R0_rect': array([1., 0., 0., 0., 1., 0., 0., 0., 1.]),
 'Tr_velo_to_cam': array([-0.0361133 , -0.99835228,  0.04459329,  0.07      , -0.02594949,
        -0.04367056, -0.99870892, -0.25      ,  0.99901074, -0.03722384,
        -0.02432964, -0.4       ])}